server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
    # 유레카 서버에 자신을 등록할지 여부 (true: 등록 O, false: 등록 X)
    register-with-eureka: true
    # 유레카 서버로부터 인스턴스 정보를 가져올지 여부
    fetch-registry: true
    service-url:
      # 유레카 서버 주소
      defaultZone: http://127.0.0.1:8761/eureka
